# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 879439f9d26df3a4c0bf5768309965ee39aab1fd84515e8a0608e431e534d5343f0480a8af8c852b2a04a422165daa7cb4f7e7a187ef6dee9a8c946358de2553

test:
  secret_key_base: 629f198219fa84a4c2a16cd8a4b3f27c67117e6edb925d82233afcd889da9c3228431cdce79f8a9360ec3d3946ae217aa42bb057cb81230ff0c33bf64610ea5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
